
import javax.swing.JOptionPane;
import dao.DbOperations;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author siam
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        signUpTextFieldId = new javax.swing.JTextField();
        signUpTextFieldFirstName = new javax.swing.JTextField();
        signUpTextFieldLastName = new javax.swing.JTextField();
        signUpTextFieldPhoneNo = new javax.swing.JTextField();
        signUpTextFieldEmail = new javax.swing.JTextField();
        signUpTextFieldAddress = new javax.swing.JTextField();
        signUpTextFieldConfirmPassword = new javax.swing.JTextField();
        signUpTextFieldPassword = new javax.swing.JTextField();
        signUpButtonEnter = new java.awt.Button();
        jLabel10 = new javax.swing.JLabel();
        signUpComboBox = new javax.swing.JComboBox<>();
        SignUpBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sign Up");

        jLabel2.setText("ID");

        jLabel3.setText("First Name");

        jLabel4.setText("Last Name");

        jLabel5.setText("Phone no");

        jLabel6.setText("Email");

        jLabel7.setText("Address");

        jLabel8.setText("Password");

        jLabel9.setText("Cofirm Password");

        signUpTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpTextFieldIdActionPerformed(evt);
            }
        });

        signUpTextFieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpTextFieldFirstNameActionPerformed(evt);
            }
        });

        signUpTextFieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpTextFieldLastNameActionPerformed(evt);
            }
        });

        signUpTextFieldPhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpTextFieldPhoneNoActionPerformed(evt);
            }
        });

        signUpTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpTextFieldEmailActionPerformed(evt);
            }
        });

        signUpTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpTextFieldAddressActionPerformed(evt);
            }
        });

        signUpTextFieldConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpTextFieldConfirmPasswordActionPerformed(evt);
            }
        });

        signUpTextFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpTextFieldPasswordActionPerformed(evt);
            }
        });

        signUpButtonEnter.setLabel("ENTER");
        signUpButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonEnterActionPerformed(evt);
            }
        });

        jLabel10.setText("Department");

        signUpComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "EEE", "ENGLISH", "TEXTILE", "SOCIOLOGY", "LAW", "BBA", "JOURNALISM" }));
        signUpComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SignUpBack.setText("BACK");
        SignUpBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SignUpBack, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(260, 260, 260)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(signUpButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(signUpTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(signUpTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(signUpTextFieldPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(signUpTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(signUpTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(signUpTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(123, 123, 123)
                                .addComponent(signUpTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(signUpComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(signUpTextFieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SignUpBack, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(signUpTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(signUpTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(signUpTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(signUpTextFieldPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(signUpTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(signUpTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(signUpTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(signUpTextFieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(signUpComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(signUpButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpTextFieldIdActionPerformed

    private void signUpTextFieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpTextFieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpTextFieldFirstNameActionPerformed

    private void signUpTextFieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpTextFieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpTextFieldLastNameActionPerformed

    private void signUpTextFieldPhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpTextFieldPhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpTextFieldPhoneNoActionPerformed

    private void signUpTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpTextFieldEmailActionPerformed

    private void signUpTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpTextFieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpTextFieldAddressActionPerformed

    private void signUpTextFieldConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpTextFieldConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpTextFieldConfirmPasswordActionPerformed

    private void signUpTextFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpTextFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpTextFieldPasswordActionPerformed

    private void signUpButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonEnterActionPerformed
        // TODO add your handling code here:
            String id = signUpTextFieldId.getText();
            String firstName =signUpTextFieldFirstName.getText();
            String lastName = signUpTextFieldLastName.getText();
            String phoneNo = signUpTextFieldPhoneNo.getText();
            String email = signUpTextFieldEmail.getText();
            String address = signUpTextFieldAddress.getText();
            String password = signUpTextFieldPassword.getText();
            String confirmPassword = signUpTextFieldConfirmPassword.getText();
            String department=signUpComboBox.getSelectedItem().toString();
            if(id.equals("") || firstName.equals("") || lastName.equals("") || phoneNo.equals("") || email.equals("")
                    || address.equals("") || password.equals("")||confirmPassword.equals("") || department.equals("")){
                JOptionPane.showMessageDialog(SignUp.this, "Please fill up!");
                return;
            }
            if(!password.equals(confirmPassword)){
                JOptionPane.showMessageDialog(SignUp.this, "Password didn't match");
                return;
            }
            System.out.println(department);
        try {
            addUser(id, firstName, lastName, phoneNo, email, address, password,department);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_signUpButtonEnterActionPerformed

    private void SignUpBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBackActionPerformed
        // TODO add your handling code here:
        new SignIn().setVisible(true);
        dispose();
    }//GEN-LAST:event_SignUpBackActionPerformed
 private void addUser(String id, String firstName, String lastName, String phoneNo, String email, String address, String password,String department) throws ClassNotFoundException {
        String insertUser = "INSERT INTO studentlist (student_id, first_name, last_name, phone_no, email_address, address, password,due,department_code) " +
                "VALUES (" + id + ", '" + firstName + "', '" + lastName + "', '" + phoneNo + "', '" + email + "', '" + address + "', '" + password + "',0,'" + department + "')";
        if(DbOperations.setDataOrDelete(insertUser,"Successfully signed up") ){
           int idd;
            idd = Integer.parseInt(id);
        new HomePage(idd).setVisible(true);
                                    dispose();
        }


    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignUpBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Button signUpButtonEnter;
    private javax.swing.JComboBox<String> signUpComboBox;
    private javax.swing.JTextField signUpTextFieldAddress;
    private javax.swing.JTextField signUpTextFieldConfirmPassword;
    private javax.swing.JTextField signUpTextFieldEmail;
    private javax.swing.JTextField signUpTextFieldFirstName;
    private javax.swing.JTextField signUpTextFieldId;
    private javax.swing.JTextField signUpTextFieldLastName;
    private javax.swing.JTextField signUpTextFieldPassword;
    private javax.swing.JTextField signUpTextFieldPhoneNo;
    // End of variables declaration//GEN-END:variables
}
