/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;


import dao.DbOperations;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author siam
 */
public class HomePageAdmin extends javax.swing.JFrame {

    /**
     * Creates new form HomePageAdmin
     */
    public HomePageAdmin() throws ClassNotFoundException {
        initComponents();
        int totalBook=DbOperations.getTotalBook();
        HomePageAdminTotalBook.setText("Total Book : "+totalBook);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePageAdminAddBook = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        HomePageAdminBookId = new javax.swing.JTextField();
        HomePageAdminStudentId = new javax.swing.JTextField();
        HomePageAdminComboBox = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HomePageTextFieldSearch = new javax.swing.JTextField();
        HomePageSearchByComboBox = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        HomePageAdminTotalBook = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HomePageAdminAddBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HomePageAdminAddBook.setText("Add Book");
        HomePageAdminAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePageAdminAddBookActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Delete Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        HomePageAdminBookId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePageAdminBookIdActionPerformed(evt);
            }
        });

        HomePageAdminComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BORROW","RETURN" }));

        jButton2.setText("ENTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Book ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Student ID");

        HomePageTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePageTextFieldSearchActionPerformed(evt);
            }
        });

        HomePageSearchByComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Book Name", "Book ID", "Author's Name",  "Department" }));

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        HomePageAdminTotalBook.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HomePageAdminStudentId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HomePageAdminBookId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HomePageAdminComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HomePageAdminAddBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HomePageTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomePageAdminTotalBook, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(HomePageSearchByComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(20, 20, 20)))))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HomePageAdminComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HomePageAdminBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HomePageAdminStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HomePageAdminAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addGap(31, 31, 31)
                .addComponent(HomePageAdminTotalBook, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomePageTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomePageSearchByComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomePageAdminAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePageAdminAddBookActionPerformed
        // TODO add your handling code here:
        new AddBook().setVisible(true);
        dispose();
        return;
    }//GEN-LAST:event_HomePageAdminAddBookActionPerformed

    private void HomePageAdminBookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePageAdminBookIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomePageAdminBookIdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String studentId=HomePageAdminStudentId.getText();
        String bookId=HomePageAdminBookId.getText();
        if(studentId.equals("") || bookId.equals("") ){
            JOptionPane.showMessageDialog(HomePageAdmin.this, "Can't leave blank !");
            return;
        }
        int student_id=Integer.parseInt(studentId);
        int book_id=Integer.parseInt(bookId);
        String type=HomePageAdminComboBox.getSelectedItem().toString();
         int availablity=0;
        if(type.equals("BORROW")){
           
            int due=0;
            try {
                due = DbOperations.getDue(student_id);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomePageAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(due>0){
                JOptionPane.showMessageDialog(HomePageAdmin.this, "Student must return borrowed book which last date have passed ! !");
                return;
            }
            
            try {
                availablity = DbOperations.getAvailablity(book_id);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomePageAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(availablity>0){
               String query="INSERT INTO borrowedlist(book_id,student_id) VALUES("+book_id+","+student_id+");";
                DbOperations.setDataOrDelete(query,"Book Borrowed");
            }
            else{
                 JOptionPane.showMessageDialog(HomePageAdmin.this, "Not available right now !");
            }
            try {
                new HomePageAdmin().setVisible(true);
                dispose();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomePageAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        else{
            
            
                    String query="DELETE FROM borrowedlist WHERE book_id="+book_id+" AND student_id="+student_id+";";
                 if(DbOperations.setDataOrDelete(query, "Returned successfully")){
                     try {
                         if(DbOperations.shouldDelete(book_id)){
                           query="DELETE FROM booklist WHERE book_id="+book_id+";"; 
                           DbOperations.setDataOrDelete(query, "Deleted successfullyyyy");
                         }
                     } catch (ClassNotFoundException ex) {
                         Logger.getLogger(DeleteBook.class.getName()).log(Level.SEVERE, null, ex);
                     }
                 } 
//      
                try { new HomePageAdmin().setVisible(true);
                dispose();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomePageAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }     
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        new DeleteBook().setVisible(true);
        dispose();
        return;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void HomePageTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePageTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomePageTextFieldSearchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String searchBy=HomePageSearchByComboBox.getSelectedItem().toString();
        String searchingWord=HomePageTextFieldSearch.getText();
        if(searchingWord.equals("")){
            JOptionPane.showMessageDialog(HomePageAdmin.this, "Can't leave blank !");
            return;
        }
        new BookListAdmin(searchBy,searchingWord).setVisible(true);
        dispose();

        //        case "CSE":
        //                break;
        //
        //            case "EEE":
        //                break;
        //            case "ENGLISH":
        //                break;
        //
        //            case "TEXTILE":
        //                break;
        //            case "SOCIOLOGY":
        //                break;
        //                case "LAW":
        //                break;
        //                case "BBA":
        //                break;
        //                case "JOURNALISM":
        //                break;

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomePageAdminAddBook;
    private javax.swing.JTextField HomePageAdminBookId;
    private javax.swing.JComboBox<String> HomePageAdminComboBox;
    private javax.swing.JTextField HomePageAdminStudentId;
    private javax.swing.JLabel HomePageAdminTotalBook;
    private javax.swing.JComboBox<String> HomePageSearchByComboBox;
    private javax.swing.JTextField HomePageTextFieldSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
